/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/shark.glb -o src/components/Shark.jsx -r public -k 
*/

import React, { useEffect, useId, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'

export function Shark(props) {
  const { nodes, materials } = useGLTF('/models/shark.glb')
  const group = useRef()

  useEffect(()=>{

    const groupWorldPosition = new THREE.Vector3()
    group.current.getWorldPosition(groupWorldPosition)

    group.current.children.forEach((mesh) => {
      mesh.originalPosition = mesh.position.clone()
      const meshWorldPosition = new THREE.Vector3()
      mesh.getWorldPosition(meshWorldPosition)

      mesh.directionVector = meshWorldPosition.clone().sub(groupWorldPosition).normalize()
      mesh.targetPosition = mesh.originalPosition.clone().add(mesh.directionVector.clone().multiplyScalar(3))
    });
  },[])

  const scrollData = useScroll()

  useFrame(()=>{
    group.current.children.forEach((mesh)=>{

      if(scrollData.offset < 0.0001){
        if(mesh.name === "origin"){
          mesh.visible = true
        }else{
          mesh.visible = false
        }
      }else{
        if(mesh.name === "origin"){
          mesh.visible = false
        }else{
          mesh.visible = true
        }
      }

      mesh.position.x = THREE.MathUtils.lerp(
        mesh.originalPosition.x,
        mesh.targetPosition.x,
        scrollData.offset,
      )
      mesh.position.y = THREE.MathUtils.lerp(
        mesh.originalPosition.y,
        mesh.targetPosition.y,
        scrollData.offset,
      )
      mesh.position.z = THREE.MathUtils.lerp(
        mesh.originalPosition.z,
        mesh.targetPosition.z,
        scrollData.offset,
      )
    })
  })

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh name="Heart_Full_cell" geometry={nodes.Heart_Full_cell.geometry} material={materials.Red} position={[-0.001, -0.471, -0.005]} />
      <mesh name="Heart_Full_cell001" geometry={nodes.Heart_Full_cell001.geometry} material={materials.Red} position={[0.147, -0.29, 0.183]} />
      <mesh name="Heart_Full_cell002" geometry={nodes.Heart_Full_cell002.geometry} material={materials.Red} position={[-0.353, 0.086, -0.129]} />
      <mesh name="Heart_Full_cell003" geometry={nodes.Heart_Full_cell003.geometry} material={materials.Red} position={[-0.303, 0.173, 0.059]} />
      <mesh name="Heart_Full_cell004" geometry={nodes.Heart_Full_cell004.geometry} material={materials.Red} position={[0.307, 0.18, 0.062]} />
      <mesh name="Heart_Full_cell005" geometry={nodes.Heart_Full_cell005.geometry} material={materials.Red} position={[-0.139, -0.134, -0.157]} />
      <mesh name="Heart_Full_cell006" geometry={nodes.Heart_Full_cell006.geometry} material={materials.Red} position={[-0.357, 0.092, 0.11]} />
      <mesh name="Heart_Full_cell007" geometry={nodes.Heart_Full_cell007.geometry} material={materials.Red} position={[-0.096, -0.39, -0.082]} />
      <mesh name="Heart_Full_cell008" geometry={nodes.Heart_Full_cell008.geometry} material={materials.Red} position={[0.337, 0.004, -0.169]} />
      <mesh name="Heart_Full_cell009" geometry={nodes.Heart_Full_cell009.geometry} material={materials.Red} position={[0.232, -0.117, -0.172]} />
      <mesh name="Heart_Full_cell010" geometry={nodes.Heart_Full_cell010.geometry} material={materials.Red} position={[0.221, -0.015, 0.192]} />
      <mesh name="Heart_Full_cell011" geometry={nodes.Heart_Full_cell011.geometry} material={materials.Red} position={[0.119, 0.105, 0.164]} />
      <mesh name="Heart_Full_cell012" geometry={nodes.Heart_Full_cell012.geometry} material={materials.Red} position={[0.001, -0.409, -0.085]} />
      <mesh name="Heart_Full_cell013" geometry={nodes.Heart_Full_cell013.geometry} material={materials.Red} position={[0.363, 0.057, 0.127]} />
      <mesh name="Heart_Full_cell014" geometry={nodes.Heart_Full_cell014.geometry} material={materials.Red} position={[-0.252, -0.083, -0.19]} />
      <mesh name="Heart_Full_cell015" geometry={nodes.Heart_Full_cell015.geometry} material={materials.Red} position={[-0.121, 0.057, 0.196]} />
      <mesh name="Heart_Full_cell016" geometry={nodes.Heart_Full_cell016.geometry} material={materials.Red} position={[0.403, -0.001, -0.06]} />
      <mesh name="Heart_Full_cell017" geometry={nodes.Heart_Full_cell017.geometry} material={materials.Red} position={[-0.002, -0.456, 0.136]} />
      <mesh name="Heart_Full_cell018" geometry={nodes.Heart_Full_cell018.geometry} material={materials.Red} position={[0.351, -0.123, -0.106]} />
      <mesh name="Heart_Full_cell019" geometry={nodes.Heart_Full_cell019.geometry} material={materials.Red} position={[-0.4, -0.004, 0.056]} />
      <mesh name="Heart_Full_cell020" geometry={nodes.Heart_Full_cell020.geometry} material={materials.Red} position={[-0.028, -0.281, -0.083]} />
      <mesh name="Heart_Full_cell021" geometry={nodes.Heart_Full_cell021.geometry} material={materials.Red} position={[-0.297, -0.187, 0.004]} />
      <mesh name="Heart_Full_cell022" geometry={nodes.Heart_Full_cell022.geometry} material={materials.Red} position={[0.299, -0.188, 0.013]} />
      <mesh name="Heart_Full_cell023" geometry={nodes.Heart_Full_cell023.geometry} material={materials.Red} position={[-0.211, -0.261, -0.098]} />
      <mesh name="Heart_Full_cell024" geometry={nodes.Heart_Full_cell024.geometry} material={materials.Red} position={[0.093, 0.2, 0.022]} />
      <mesh name="Heart_Full_cell025" geometry={nodes.Heart_Full_cell025.geometry} material={materials.Red} position={[0.219, 0.212, 0.015]} />
      <mesh name="Heart_Full_cell026" geometry={nodes.Heart_Full_cell026.geometry} material={materials.Red} position={[-0.007, 0.106, -0.146]} />
      <mesh name="Heart_Full_cell027" geometry={nodes.Heart_Full_cell027.geometry} material={materials.Red} position={[0.336, 0.111, -0.115]} />
      <mesh name="Heart_Full_cell028" geometry={nodes.Heart_Full_cell028.geometry} material={materials.Red} position={[0.19, 0.182, -0.12]} />
      <mesh name="Heart_Full_cell029" geometry={nodes.Heart_Full_cell029.geometry} material={materials.Red} position={[0.067, -0.4, 0.052]} />
      <mesh name="Heart_Full_cell030" geometry={nodes.Heart_Full_cell030.geometry} material={materials.Red} position={[-0.378, 0.109, 0]} />
      <mesh name="Heart_Full_cell031" geometry={nodes.Heart_Full_cell031.geometry} material={materials.Red} position={[-0.091, -0.387, 0.053]} />
      <mesh name="Heart_Full_cell032" geometry={nodes.Heart_Full_cell032.geometry} material={materials.Red} position={[-0.197, -0.246, 0.087]} />
      <mesh name="Heart_Full_cell033" geometry={nodes.Heart_Full_cell033.geometry} material={materials.Red} position={[-0.314, -0.011, 0.149]} />
      <mesh name="Heart_Full_cell034" geometry={nodes.Heart_Full_cell034.geometry} material={materials.Red} position={[0.169, -0.137, 0.184]} />
      <mesh name="Heart_Full_cell035" geometry={nodes.Heart_Full_cell035.geometry} material={materials.Red} position={[-0.395, -0.072, -0.011]} />
      <mesh name="Heart_Full_cell036" geometry={nodes.Heart_Full_cell036.geometry} material={materials.Red} position={[0.001, -0.298, 0.18]} />
      <mesh name="Heart_Full_cell037" geometry={nodes.Heart_Full_cell037.geometry} material={materials.Red} position={[-0.163, 0.087, -0.176]} />
      <mesh name="Heart_Full_cell038" geometry={nodes.Heart_Full_cell038.geometry} material={materials.Red} position={[-0.113, 0.201, -0.018]} />
      <mesh name="Heart_Full_cell039" geometry={nodes.Heart_Full_cell039.geometry} material={materials.Red} position={[0.382, 0.112, 0]} />
      <mesh name="Heart_Full_cell040" geometry={nodes.Heart_Full_cell040.geometry} material={materials.Red} position={[0.003, 0.03, 0.018]} />
      <mesh name="Heart_Full_cell041" geometry={nodes.Heart_Full_cell041.geometry} material={materials.Red} position={[0.167, -0.277, 0.03]} />
      <mesh name="Heart_Full_cell042" geometry={nodes.Heart_Full_cell042.geometry} material={materials.Red} position={[-0.167, 0.187, 0.113]} />
      <mesh name="Heart_Full_cell043" geometry={nodes.Heart_Full_cell043.geometry} material={materials.Red} position={[-0.273, 0.1, 0.163]} />
      <mesh name="Heart_Full_cell044" geometry={nodes.Heart_Full_cell044.geometry} material={materials.Red} position={[-0.217, -0.126, 0.191]} />
      <mesh name="Heart_Full_cell045" geometry={nodes.Heart_Full_cell045.geometry} material={materials.Red} position={[-0.347, -0.12, -0.104]} />
      <mesh name="Heart_Full_cell046" geometry={nodes.Heart_Full_cell046.geometry} material={materials.Red} position={[0.198, -0.008, -0.205]} />
      <mesh name="Heart_Full_cell047" geometry={nodes.Heart_Full_cell047.geometry} material={materials.Red} position={[0.38, -0.081, 0.036]} />
      <mesh name="Heart_Full_cell048" geometry={nodes.Heart_Full_cell048.geometry} material={materials.Red} position={[0.295, -0.139, 0.158]} />
      <mesh name="Heart_Full_cell049" geometry={nodes.Heart_Full_cell049.geometry} material={materials.Red} position={[-0.347, -0.121, 0.108]} />
      <mesh name="Heart_Full_cell050" geometry={nodes.Heart_Full_cell050.geometry} material={materials.Red} position={[0.126, -0.244, -0.116]} />
      <mesh name="Heart_Full_cell051" geometry={nodes.Heart_Full_cell051.geometry} material={materials.Red} position={[0.148, 0.076, -0.195]} />
      <mesh name="Heart_Full_cell052" geometry={nodes.Heart_Full_cell052.geometry} material={materials.Red} position={[-0.316, 0.008, -0.16]} />
      <mesh name="Heart_Full_cell053" geometry={nodes.Heart_Full_cell053.geometry} material={materials.Red} position={[-0.122, -0.272, 0.193]} />
      <mesh name="Heart_Full_cell054" geometry={nodes.Heart_Full_cell054.geometry} material={materials.Red} position={[0.036, -0.118, -0.144]} />
      <mesh name="Heart_Full_cell055" geometry={nodes.Heart_Full_cell055.geometry} material={materials.Red} position={[0.082, -0.405, -0.072]} />
      <mesh name="Heart_Full_cell056" geometry={nodes.Heart_Full_cell056.geometry} material={materials.Red} position={[-0.285, 0.173, -0.079]} />
      <mesh name="Heart_Full_cell057" geometry={nodes.Heart_Full_cell057.geometry} material={materials.Red} position={[0.003, -0.133, 0.199]} />
      <mesh name="Heart_Full_cell058" geometry={nodes.Heart_Full_cell058.geometry} material={materials.Red} position={[0.273, 0.114, 0.169]} />
      <mesh name="Heart_Full_cell059" geometry={nodes.Heart_Full_cell059.geometry} material={materials.Red} position={[0.227, -0.216, -0.107]} />
      <mesh name="origin" geometry={nodes.origin.geometry} material={materials.Red} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/shark.glb')
